CREATE DATABASE FinalProject;
USE FinalProject;

CREATE TABLE schools (
    SchoolID INT AUTO_INCREMENT,
    School VARCHAR(500),
    School_Rank VARCHAR(500),
    Setting VARCHAR(100),
    Address VARCHAR(250),
    City VARCHAR(100),
    State VARCHAR(50),
    Zipcode INT,
    Tuition_and_Fees FLOAT,
    Average_Cost_After_Aid FLOAT,
    Undergraduate_Enrollment INT,
    Acceptance_Rate FLOAT,
    Application_Date VARCHAR(50),
    SAT_Lower INT,
    SAT_Upper INT,
    ACT_Lower INT,
    ACT_Upper INT,
    High_School_GPA FLOAT,
    Room_and_Board FLOAT,
    Average_Need_Based_Aid_Package FLOAT,
    Bibliometric_rank INT,
    Graduate_Enrollment INT,
    Total_Enrollment INT,
    Full_Time_Students INT,
    Student_Faculty_Ratio INT,
    Classes_Under20_Students FLOAT,
    Male_Student_Percentage FLOAT,
    Female_Student_Percentage FLOAT,
    Minority_Enrollment VARCHAR(150),
    Minority_Percentage INT,
    Ethnic_Group_2 VARCHAR(150),
    Ethnic_Percentage_2 INT,
    Ethnic_Group_3 VARCHAR(150),
    Ethnic_Percentage_3 INT,
    Ethnic_Group_4 VARCHAR(150),
    Ethnic_Percentage_4 INT,
    Ethnic_Group_5 VARCHAR(150),
    Ethnic_Percentage_5 INT,
    Ethnic_Group_6 VARCHAR(150),
    Ethnic_Percentage_6 INT,
    Ethnic_Group_7 VARCHAR(150),
    Ethnic_Percentage_7 INT,
    Ethnic_Group_8 VARCHAR(150),
    Ethnic_Percentage_8 INT,
    Graduation_Rate FLOAT,
    Percentage_of_Graduating_Students_Who_Borrowed FLOAT,
    Average_Debt_at_Graduation FLOAT,
    Median_Starting_Salary FLOAT,
    Latitude FLOAT,
    Longitude FLOAT,
    PRIMARY KEY (schoolid)
);

SELECT * FROM schools;
DROP TABLE schools;